### PR TITLE
update the / redirection

### LINKED ISSUE #83: consider a more useful `/` redirect
http://registry-sandbox.k8s.io/ redirects to https://github.com/kubernetes/k8s.io/tree/main/registry.k8s.io which doesn't actually contain anything we're using or any docs.

https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io) is probably a better URL for now?

cc @dims @ameukam 

We should also probably apply #79 to paths like this, since we'll update it in the future.

### PR DESCRIPTION
**Pull request by justina777**
Fixes #83

/cc @ameukam

### CODE REVIEW

**Comment by upodroid** [comment]
Please sign the CLA and rebase this PR.

**Comment by justina777** [comment]
I've signed the CLA and used the /easycla command /easycla to update the status, but the status didn't update. Is there anything I should do?

**Comment by upodroid** [comment]
PR is ready for review. Arnaud will review it when he is free. Keep an eye out for comments about rebasing as we have a few open PRs against the same set of files. Try to resolve conflicts when you get notified about it as it blocks PRs from being merged.

**Comment by ameukam** [comment]
/lgtm
/approve

Thank you!

**Pull request merged**
