### PR TITLE
hack: bump ko to 0.11.2

### PR DESCRIPTION
**Pull request by ameukam**
Diff:
 - https://github.com/google/ko/compare/v0.9.3...v0.11.2

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @BenTheElder

**Comment by BenTheElder** [comment]
https://github.com/google/ko/releases v0.10.0 has a lot of changes, the rest is largely dep updates and fixes for go 1.18
still reading v0.10 log

**Pull request merged**
