### PR TITLE
update ip addresses

### PR DESCRIPTION
**Pull request by ameukam**
Update ip addresses from AWS IP ranges.
Also shebang to better support bash installation on other platforms.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by BenTheElder** [comment]
In the future I recommend generated changes in a separate commit, but the non-generated changes are small and the total number of files is smile so it's fine 😅

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by ameukam** [comment]
> In the future I recommend generated changes in a separate commit, but the non-generated changes are small and the total number of files is smile so it's fine 😅 

Possibly, a periodic generating the changes for us?

**Pull request merged**
